# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170313_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Album',
            new_name='Playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Playlist'),
        ),
        migrations.AddField(
            model_name='addpreferences',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Playlist'),
        ),
    ]
